language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="crunch"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
 matrix:
   - DISTRO=debian-unstable OCAML_VERSION=4.03.0
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.03.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.04.0
   - DISTRO=centos-7 OCAML_VERSION=4.03.0
   - DISTRO=alpine OCAML_VERSION=4.04.0
